### ISSUE TITLE
[Bug] Fail fixture loading: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again

### ISSUE THREAD

**Issue by abulojoshua1** [getbigger-io/prisma-fixtures#3]
### Your Environment
Incompatibility with `Prisma v3+`
```
Fail fixture loading: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/node_modules/@getbigger-io/prisma-fixtures-cli/node_modules/.prisma/client/index.js:3:11)
    at Object.<anonymous> (/node_modules/@getbigger-io/prisma-fixtures-cli/dist/util/createConnection.js:16:24)
    at Generator.next (<anonymous>)
    at /node_modules/@getbigger-io/prisma-fixtures-cli/dist/util/createConnection.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/@getbigger-io/prisma-fixtures-cli/dist/util/createConnection.js:4:12)
    at Object.createConnection (/node_modules/@getbigger-io/prisma-fixtures-cli/dist/util/createConnection.js:15:12)
    at Object.<anonymous> (/node_modules/@getbigger-io/prisma-fixtures-cli/dist/cli.js:58:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by earthpyy** [comment]
I'm having the same problem. Running on Prisma 4.1.x

**Comment by nmacherey** [comment]
@earthpyy the next release will be compatible with prisma 4. You can try the last commit on the master branch

**Comment by earthpyy** [comment]
@nmacherey Glad to hear that! Looking forward for the release 😄

**Comment by nikechanhk** [comment]
> @earthpyy the next release will be compatible with prisma 4. You can try the last commit on the master branch

This project should deserve more star

**Comment by mehdibo** [comment]
I did this and the issue was solved:
```shell
rm -rf node_modules/@getbigger-io/prisma-fixtures-cli/node_modules/.prisma
yarn prisma generate
```
